version: '3.8'
services:
  cartoonizer-front:
    image: cartoonizer-front
    network_mode: "host"
    volumes:
      - /var/cartoonizer:/var/cartoonizer
    environment:
      - bot_token=6381166597:AAHE4A8xMslLBspJ_-L5CBJ48INbfJCCvY4

  cartoonizer-back:
    image: cartoonizer-back
    network_mode: "host"
    volumes:
      - /var/cartoonizer:/var/cartoonizer